### ISSUE TITLE
Infrastructure to skip distributions and releases

### ISSUE THREAD

**Issue by schwern** [evalEmpire/gitpan#67]
Add infrastructure to skip certain distributions and releases.  The information will be in the configuration file like so.

```
skip:
    dists:
        - perl
        - parrot
        - parrot-cfg
    releases:
        - SOMEONE/Some-Broken-Release-0.45.tar.gz
```

See #37 for details.
