### ISSUE TITLE
Infrastructure to transform distribution names

### ISSUE THREAD

**Issue by schwern** [evalEmpire/gitpan#68]
Add the ability to change the name of a distribution or what release a distribution is a part of.  Have it read the information from the config file.

```
dist_transforms:
    dists:
        uri: URIC
        Webservice-Google-Suggest: WebService-Google-Suggest
    releases:
        SOMEONE/Some-Rogue-Release-0.02.tar.gz: Some-Other-Distribution
        MARCEL/-0.01.tar.gz: Bi
```

See #37, #8 and #35
