### ISSUE TITLE
Ability to skip individual releases in the config

### ISSUE THREAD

**Issue by schwern** [evalEmpire/gitpan#81]
There's a lot of archives which do not extract for various reasons.  This kills the import of the whole distribution.

Add the ability to skip individual releases in the config.

The config is part of the existing "skip" keyword.  Add a list of "releases".  The releases use the short_path.  Example...

```
skip:
    dists:
        - perl
        - parrot
        - parrot-cfg
    releases:
        - MJD/valgrind/ALL.tgz
        - MJD/valgrind/ERRORS.tgz
        - SCHUBIGER/scripts/crypt-0.1.tar.gz
        - GSLONDON/iperl.20040205.html.tar.gz
        - GSLONDON/iperl.20040205.zip
```
